version: '3'
services:
  app:
    image: santos-api:1.0
    ports:
      - 3333:3333
  mongodb:
    image: mongo 
    ports:
      - 27017:27017
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root 
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongo-data:/data/db 
  mongo-express:
    image: mongo-express 
    ports:
      - 8080:8081
    environment:               
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local
  