version: '3'

services:
  api:
    image: api-ecossistema:1.0
    ports:
      - 9000:9000
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DIALECT=${DB_DIALECT}
  mysql:
    image: mysql:latest 
    ports:
      - 3306:3306 
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_DATABASE=app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest 
    links:
      -  mysql 
    ports: 
      - 80:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  data: 